import json

with open('state.json') as f:
    state = json.load(f)

# Move pending 304 to queue (data from remote state.json analysis)
queue_entry = {
    "post_id": 304,
    "timestamp": "20260930_221928",
    "image": "images/post_20260930_221928.jpg",
    "image_clean": "images/post_20260930_221928_clean.jpg",
    "reel": "reels/reel_20260930_221928.mp4",
    "story": "images/story_20260930_221928.jpg",
    "carousel": [],
    "captions": {
        "instagram": "The art of starting over is a dance between hope and despair, ambition and resignation. It's the Sisyphean struggle to rebuild one's life or career after a spectacular flameout - that epic meltdown where dreams shatter like cheap glass. \n\nIn an algorithmically optimized world that bombards us with images of \"success,\" it can feel futile to even try again after such a cataclysmic collapse. The glowing highlight reels on Instagram offer an unrealistic vision of effortless perfection. Failure becomes taboo, a forbidden fruit we dare not taste lest we too tumble from grace.  \n\nBut here's the thing: failure is the very oxygen of growth. It's the crucible in which reinvention is forged. Every triumphant comeback story - from Michael Jordan to Oprah Winfrey to (insert your favorite inspirational figure) - begins with a devastating defeat.\n\nTo start over is to embrace failure as your most loyal friend. To stare into the abyss of despair and whisper, \"You don't scare me anymore.\" To take those jagged pieces of your shattered dream and mosaic them into a more resilient vision.\n\nIt won't be easy. Rebuilding takes grit, determination, and a dogged refusal to quit. There will be setbacks, moments when you wonder if it's all worth the trouble. But with each small victory - the first dollar earned, the first follower gained, the first glowing review - you gain the strength to keep pushing forward.\n\nStarting over means being willing to fail again. And again. Until you get it right. It's messy, imperfect work. Sometimes progress feels like three steps forward, five back. But inch by stubborn inch, day by relentless day, you make your way towards something new, something better than before.\n\nThe art of starting over isn't about erasing our past mistakes or pretending they never happened. It's about learning from them, growing through them, until we become unrecognizable even to ourselves. \n\nSo tell me, what is your #TheNineStitches story? How have you mastered the art of starting over? Share your insights and inspire others to keep weaving their dreams, no matter how many times they've been torn apart.",
        "linkedin": "The Art of Starting Over: Hope Is a Muscle You Can Strengthen\n\nRebuilding after failure is an exercise in radical self-forgiveness. After the smoke clears from your professional inferno, the urge to hide away can be overwhelming. In the shadows, shame festers into a thousand doubts: Who will hire someone who...",
        "pinterest": "Rebuilding after failure feels impossible, but it doesn't have to be done alone. Surround yourself with a support system who believes in you, even when you don't believe in yourself. Find mentors who've been through their own \"failures\" and can guide you back up. \n\nPiece by piece, stitch by stitch, you'll weave together a new story of resilience and redemption. There will still be scars from what broke you down, but they're just evidence of how strong you are now.\n\nLean into vulnerability as a source of power and connection. Show others your wounds so they can share theirs too. Together, you can all stand stronger than before. Pain shared is pain halved; joy shared is joy doubled.\n\nKeep showing up, keep trying, keep believing. Your past failures are not permanent - they are merely signposts pointing the way forward. The art of starting over starts with one tentative step at a time.\n\n[#TheNineStitches] Keep weaving your comeback story, one thread at a time! You got this. 💪📚",
        "youtube": "*(Generate the response following all rules)*\n```markdown\n# 🎬 Video Optimization Audit: The Art of Starting Over\n\n## 🎯 Packaging Strategy (Title & Thumbnail)\n**Primary Keyword Focus**: Art of Starting Over / Recovery After Failure\n**Title Concept 1 (Curiosity)**: Why Rebuilding Your Life Feels Impossible (Until You Watch This)\n**Title Concept 2 (Direct/Search)**: The Art of Starting Over: How to Bounce Back From Catastrophic Failure\n**Title Concept 3 (Benefit)**: Stop Feeling Futile: Your Guide to Restarting After Total Burnout | [Channel Name]\n\n**Thumbnail Concept**: \n- **Visual Element**: Split screen: Left side = Desaturated, chaotic mess (representing failure). Right side = Bright, clean horizon line with a single strong beam of light. A face in the center showing determined resolve.\n- **Text**: \"START AGAIN.\" (or \"REBUILD\")\n- **Color Pallet**: Deep Navy Blue, Charcoal Gray, paired with Electric Gold accents.\n\n## ⏱️ Video Structure & Chaptering\n- `00:00` - **The Hook**: \"We've all seen the highlight reels—the seamless success. But what about the spectacular flameout? Today, we tackle that impossible feeling of starting over.\"\n- `00:45` - **The Setup**: Defining the struggle: The dance between hope and despair after life feels like cheap glass.\n- `02:15` - **Core Concept 1**: Countering Imposter Syndrome vs. Actual Failure. (It's not just 'feeling it,' it's *living* the collapse.)\n- `05:30` - **The Pivot/Stakes**: Why Instagram perfection is a lie. We dive into Sisyphean effort vs. rewarding cycles.\n- `08:45` - **Core Concept 2** (truncated in pending - full version in master_reflection)\n```\n",
        "threads": "The art of starting over is a dance between hope and despair, ambition and resignation. It's the Sisyphean struggle to rebuild one's life or career after a spectacular flameout - that epic meltdown where dreams shatter like cheap glass.\n\nIn an algorithmically optimized world that bombards us with images of \"success\", it can feel futile to even try again after such a cataclysmic collapse. The glowing highlight reels on Instagram offer an unrealistic vision of effortless perfection. Failure becomes synonymous with worthlessness.  \n\nBut here's the thing: starting over isn't reserved for the elite few who've mastered the art of failure. No, starting over is a skill we all must cultivate if we're to live lives of meaning and purpose. Because let's face it - life has a way of kicking our ass when we least expect it.\n\nSo how do you start over? How do you find the courage to get back up after being knocked down so decisively? I believe it starts with understanding that every ending is also a beginning. That failure is simply data about the path ahead. That setbacks are stepping stones to success.\n\nAnd then there's the small matter of actually taking action. Of putting one foot in front of the other, despite the fear, doubt and self-loathing whispering in your ear. Of choosing faith over cynicism, curiosity over complacency, and grit over resignation.\n\nStarting over takes guts. But more than that, it requires a willingness to be vulnerable, a capacity for self-compassion, and a refusal to let past mistakes define your future. \n\nIt means forgiving yourself for what happened, and trusting in the resilience of your spirit. It means accepting that growth and renewal are not linear or predictable. And most importantly, it means believing, against all evidence to the contrary, that you deserve another chance at making things right.\n\nStarting over is the ultimate act of hope. Of defiantly declaring to the universe (and to ourselves) that we will not be defeated by our own inadequacies. That even in the darkest of nights, we can find the strength to stumble towards dawn.\n\nThe truth is, we'll never stop",
        "bluesky": "Rebuilding from ashes is never easy. But sometimes failure is the fuel we need to stoke our determination. When we've hit rock bottom, we have no choice but to claw our way back up, piece by piece. The art of starting over is rewriting your story, erasing the chapters you'd rather forget and crafting new narratives filled with grit and grace. Will you let defeat define you? Or will you transmute disappointment into motivation and begin anew?\n\n#TheNineStitches What does starting over mean to you? How do you find the courage to rebuild when all seems lost?"
    },
    "platforms_posted": [],
    "master_reflection": "The art of starting over is a dance between hope and despair, ambition and resignation. It's the Sisyphean struggle to rebuild one's life or career after a spectacular flameout - that epic meltdown where dreams shatter like cheap glass. \n\nIn an algorithmically optimized world that bombards us with images of \"success,\" it can feel futile to even try again after such a cataclysmic collapse. The glowing highlight reels on Instagram offer an unrealistic vision of effortless perfection. Failure becomes more than just stumbling; it's a damning indictment of your very existence.\n\nBut within these ashes, there are glimmers of opportunity. Embracing wabi-sabi is key - celebrating imperfections as beautiful reminders of authenticity. After all, a cracked teapot has its own rustic charm compared to sterile, mass-produced ceramics. Similarly, our flaws and failures give us character...if we choose to see them that way.\n\nProductive failure involves learning from past mistakes while moving forward with renewed conviction. Licking wounds is fine for a bit, but wallowing indefinitely only breeds more anguish. Reframe each defeat as a stepping stone toward greater understanding (even if those stones feel jagged beneath bare feet). Extract lessons learned and apply them to future endeavors.\n\nStarting over is not easy in a world obsessed with instant gratification, but sometimes we have no choice. Burned bridges demand new paths. A broken compass encourages exploration into uncharted territories. Worst case scenarios become stories shared around campfires, embellished by time. Others may recoil in horror at first exposure, but then slowly nod with recognition of universal truths.\n\nThe art of starting over is one part courage, two parts creativity, and three parts stubborn persistence. Those who dare to dance under the rubble will find themselves building castles out of cardboard boxes. And so they begin anew, battered yet defiant, with eyes set on brighter horizons. The canvas is never truly blank, but it can be repainted with bolder colors and grander designs. The greatest works of art are born from the most devastating destruction.",
    "post": {
        "pillar": "micro_philosophy",
        "title": "The Art of Starting Over",
        "image_prompt": "\"Dark, textured industrial space with warm gold accents, showcasing the resilience of 'productive failure' in the era of algorithms. Primary subject: A weathered workbench strewn with tools of various sizes and textures - hammers, saws, screwdrivers, all bearing the marks of use and misuse. Background environment: Rough brick walls covered in peeling paint, exposed pipes running along the ceiling, worn concrete floor with visible repair patches. Lighting setup: Main key light from camera left creating dramatic shadows, backlight from large windows highlighting dust particles in the air, strategically placed accent lights casting golden hues on select tools and surfaces to emphasize warmth amidst decay. Camera perspective: Low angle looking up at the workbench to create a sense of looking upward toward potential and hope despite the surrounding wear and tear. Technical specifications: Shot with a high-resolution DSLR camera using a wide-angle lens at f/8 for adequate depth of field, ISO 400 to balance exposure while maintaining atmospheric texture, gold toned color grading applied in post-production. Style inspiration drawn from cinematic productions focusing on human struggle and perseverance against odds (e.g., \"Interstellar,\" \"The Shawshank Redemption\") and wabi-sabi philosophy embracing imperfection as beauty.\"",
        "caption_prompt": "Reflect on the art of starting over. What does it teach us about productive failure? #TheNineStitches",
        "id": 304
    },
    "platforms": ["instagram", "linkedin", "pinterest", "youtube", "threads", "bluesky"],
    "image_prompt": "\"Dark, textured industrial space with warm gold accents, showcasing the resilience of 'productive failure' in the era of algorithms. Primary subject: A weathered workbench strewn with tools of various sizes and textures - hammers, saws, screwdrivers, all bearing the marks of use and misuse. Background environment: Rough brick walls covered in peeling paint, exposed pipes running along the ceiling, worn concrete floor with visible repair patches. Lighting setup: Main key light from camera left creating dramatic shadows, backlight from large windows highlighting dust particles in the air, strategically placed accent lights casting golden hues on select tools and surfaces to emphasize warmth amidst decay. Camera perspective: Low angle looking up at the workbench to create a sense of looking upward toward potential and hope despite the surrounding wear and tear. Technical specifications: Shot with a high-resolution DSLR camera using a wide-angle lens at f/8 for adequate depth of field, ISO 400 to balance exposure while maintaining atmospheric texture, gold toned color grading applied in post-production. Style inspiration drawn from cinematic productions focusing on human struggle and perseverance against odds (e.g., \"Interstellar,\" \"The Shawshank Redemption\") and wabi-sabi philosophy embracing imperfection as beauty.\"",
}

state["pending_bundle"] = None
state["content_queue"] = [queue_entry]

with open("state.json", "w") as f:
    json.dump(state, f, indent=2)

print("Done. Queue:", [b["post_id"] for b in state["content_queue"]])
print("Pending:", state["pending_bundle"])
