#!/usr/bin/env python3
"""Wilma clean-base fallback mechanism.

When AI Horde image generation fails (403, KudosUpfront, etc.), this module
provides a pre-branded PNG from the clean pool so Wilma can keep posting
without interruption.

Usage:
    python scripts/wilma_fallback_base.py --topic "What happened..." --output forwilma/images/day_N_fallback.jpg

State files:
    forwilma/clean_bases.json  - discovered clean bases (generated by scan_wilma_clean_bases.py)
    forwilma/used_bases.json   - tracks which bases have been consumed this cycle
"""
import argparse
import json
import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FORWILMA_DIR = REPO_ROOT / "forwilma"
CLEAN_BASES_PATH = FORWILMA_DIR / "clean_bases.json"
USED_BASES_PATH = FORWILMA_DIR / "used_bases.json"


def load_clean_bases() -> list[dict]:
    """Load the clean bases list. Returns list of base dicts."""
    if not CLEAN_BASES_PATH.exists():
        raise FileNotFoundError(
            f"clean_bases.json not found. Run: python scripts/scan_wilma_clean_bases.py"
        )
    data = json.loads(CLEAN_BASES_PATH.read_text(encoding="utf-8"))
    bases = data.get("clean_bases", [])
    if not bases:
        raise RuntimeError("No clean bases available in clean_bases.json")
    return bases


def load_used_bases() -> set[str]:
    """Load the set of used base paths."""
    if not USED_BASES_PATH.exists():
        return set()
    try:
        data = json.loads(USED_BASES_PATH.read_text(encoding="utf-8"))
        return set(data.get("used", []))
    except Exception:
        return set()


def save_used_bases(used: set[str]) -> None:
    """Persist the used bases set."""
    USED_BASES_PATH.write_text(
        json.dump({"used": sorted(used)}, indent=2),
        encoding="utf-8",
    )


def pick_base(bases: list[dict], used: set[str]) -> dict | None:
    """Pick the next unused clean base. Returns None if all consumed."""
    for base in bases:
        if base["path"] not in used:
            return base
    return None


def reset_cycle() -> None:
    """Reset the used-bases tracker to start a new cycle."""
    save_used_bases(set())
    print("♻️  Clean-base cycle reset — all 13 bases available again")


def mark_used(base_path: str) -> set[str]:
    """Mark a base as used. Returns updated used set."""
    used = load_used_bases()
    used.add(base_path)
    save_used_bases(used)
    return used


def apply_wilma_branding(input_path: str, output_path: str, topic: str) -> str:
    """Apply Wilma branding (text overlay + logo) to a clean base image.
    
    Uses Wilma's own add_static_text_overlay and apply_logo_watermark functions
    from wilma_bot.py to ensure brand consistency.
    """
    sys.path.insert(0, str(REPO_ROOT))
    sys.path.insert(0, str(FORWILMA_DIR))
    
    # Import Wilma's real brand functions (same ones used in wilma_bot.py)
    try:
        from wilma_bot import add_static_text_overlay, apply_logo_watermark, LOGO_PATH
    except ImportError as e:
        raise RuntimeError(f"Cannot import Wilma brand functions: {e}")
    
    # Apply the massive text overlay box
    print(f"Applying text overlay: '{topic[:60]}...'")
    with_text = add_static_text_overlay(
        image_path=input_path,
        text=topic,
        position="center",
        font_size=60,
        opacity=0.85,
    )
    
    # Apply logo bottom-right
    print(f"Applying logo: {LOGO_PATH}")
    with_logo = apply_logo_watermark(
        image_path=with_text,
        logo_path=LOGO_PATH,
        position="bottom-right",
        width=160,
    )
    
    # Copy to output
    shutil.copy2(with_logo, output_path)
    print(f"✅ Branded image: {output_path}")
    return output_path


def get_next_base(topic: str, output_path: str) -> str | None:
    """Main entry: pick next unused base, brand it, return output path.
    
    Returns the branded output path, or None if no bases available.
    """
    bases = load_clean_bases()
    used = load_used_bases()
    
    base = pick_base(bases, used)
    
    if base is None:
        # All bases consumed — reset cycle and pick first
        reset_cycle()
        used = load_used_bases()
        base = pick_base(bases, used)
        if base is None:
            return None  # Should not happen
    
    input_path = base["path"]
    print(f"Selected base: {input_path} (text={base.get('text_pct', '?')}%)")
    
    # Apply Wilma branding
    apply_wilma_branding(input_path, output_path, topic)
    
    # Mark as used
    used = mark_used(input_path)
    remaining = len(bases) - len(used)
    print(f"📊 {remaining}/{len(bases)} bases remaining in this cycle")
    
    return output_path


def main():
    parser = argparse.ArgumentParser(description="Wilma clean-base fallback mechanism")
    parser.add_argument("--topic", required=True, help="Post topic for text overlay")
    parser.add_argument("--output", required=True, help="Output branded image path")
    parser.add_argument("--scan", action="store_true", help="Re-scan for clean bases first")
    parser.add_argument("--reset", action="store_true", help="Reset cycle (mark all unused)")
    parser.add_argument("--status", action="store_true", help="Show status of clean bases")
    args = parser.parse_args()
    
    if args.reset:
        reset_cycle()
        return
    
    if args.status:
        bases = load_clean_bases()
        used = load_used_bases()
        remaining = len(bases) - len(used)
        print(f"Total bases: {len(bases)}")
        print(f"Used: {len(used)}")
        print(f"Remaining: {remaining}")
        if used:
            print("\nUsed bases:")
            for p in sorted(used):
                print(f"  ✓ {p}")
        unused = [b for b in bases if b["path"] not in used]
        if unused:
            print(f"\nNext up: {unused[0]['path']}")
        return
    
    if args.scan:
        # Re-scan
        result = os.popen("python scripts/scan_wilma_clean_bases.py").read()
        print(result)
    
    output = get_next_base(args.topic, args.output)
    if not output:
        print("❌ No clean bases available")
        sys.exit(1)
    print(f"\n🎯 Final branded image: {output}")


if __name__ == "__main__":
    main()
